version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: part1
    ports:
      - "3307:3306"
    container_name: database_server
    

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "7070:80"
    container_name: client_php

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "6060:80"
    container_name: front

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: back

